### ISSUE TITLE
How do use the pretrained models of ICNet that are provided?

### ISSUE THREAD

**Issue by gshdong** [meetshah1995/pytorch-semseg#125]
@meetshah1995 @adam9500370 The pretrained models of ICNet come from https://github.com/meetshah1995/pytorch-semseg/pull/81. I do not how to use.

**Comment by adam9500370** [comment]
Hi, @gshdong .
After you downloaded the pretrained models, you can modify the corresponding settings in config file (refer to [configs/fcn8s_pascal.yml](https://github.com/meetshah1995/pytorch-semseg/blob/master/configs/fcn8s_pascal.yml)),
e.g., using cfg['training']['resume'] to load pretrained models.
```
model:
    arch: icnet
...
training:
    resume: icnet_cityscapes_trainval_90k.pth
...
```

Then run `python train.py --config your_config.yml` for training
or run `python validate.py --config your_config.yml --model_path icnet_cityscapes_trainval_90k.pth` for validation.

**Comment by gshdong** [comment]
@adam9500370  I run python validate.py --config icnet_cityscapes.yml --model_path icnet_cityscapes_train_30k.pth that is provided by you for validation. However, I get only 0.0198757906223 miou. How do I get your 65.86 miou. I'm confused.

**Comment by gshdong** [comment]
@adam9500370 I set img_norm=False and version="pascal" arguments in cityscapes_loader.py. However, I get 0.0516289067284 miou. I don't know what's wrong. Can you send me your successful code, my email is 9960655@qq.com. Thank you very much!

**Comment by adam9500370** [comment]
https://github.com/meetshah1995/pytorch-semseg/blob/6efd0b5baf11cb11f828390c24a5d10808a6e51c/ptsemseg/models/icnet.py#L182
https://github.com/meetshah1995/pytorch-semseg/blob/6efd0b5baf11cb11f828390c24a5d10808a6e51c/ptsemseg/models/icnet.py#L196
If you are using pytorch 0.4.1, you need to replace these lines `interp(x, output_size=get_interp_size(x, s_factor=2))` with `F.interpolate(x, size=get_interp_size(x, s_factor=2), mode='bilinear', align_corners=True)`, because it seems that `F.grid_sample` in pytorch 0.4.1 is not the same as that one in pytorch 0.3.0.

And you can create a config file (icnet_cityscapes.yml) as the followings:
```
model:
    arch: icnet
    version: cityscapes
    with_bn: False
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 1025
    img_cols: 2049
    path: cityscapes_dataset_root_path
training:
    batch_size: 1
    resume: icnet_cityscapes_train_30k.pth
```
