### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by li0128** [meetshah1995/pytorch-semseg#188]
RUNDIR: runs/fcn8s_pascal/68527
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    train(cfg, writer, logger)
  File "train.py", line 49, in train
    augmentations=data_aug,
  File "/home/lxc/PythonProjects/pytorch-semseg-master/ptsemseg/loader/pascal_voc_loader.py", line 73, in __init__
    self.setup_annotations()
  File "/home/lxc/PythonProjects/pytorch-semseg-master/ptsemseg/loader/pascal_voc_loader.py", line 199, in setup_annotations
    path = pjoin(sbd_path, "dataset/train.txt")
  File "/home/lxc/anaconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by pvbhanuteja** [comment]
2 possibilities of error 
1)
I think the issue might  be you didn't add sdb_path in config file properly ?
if not add sdb_path in the config file

2)
The data-set you have, does it contain sbd data as well ?

**Comment by li0128** [comment]
thank you @pvbhanuteja 
The reason for the error is the lack of code：
train.py 
def train(cfg, writer, logger):
    sbd_path = cfg["data"]["sbd_path"]
    t_loader = data_loader(
        sbd_path,

**Comment by li0128** [comment]
@pvbhanuteja  thank you !

**Comment by mvcaro** [comment]
@li0128 - how did you solve the problem? 


I am getting a similar error:
```
Traceback (most recent call last):
  File "/home/admin-ata168/pytorch-semseg/pytorch-semseg/validate.py", line 167, in <module>
    validate(cfg, args)

  File "/home/admin-ata168/pytorch-semseg/pytorch-semseg/validate.py", line 42, in validate
    img_size=(cfg["data"]["img_rows"], cfg["data"]["img_cols"]),

  File "/home/admin-ata168/pytorch-semseg/pytorch-semseg/ptsemseg/loader/pascal_voc_loader.py", line 73, in __init__
    self.setup_annotations()

  File "/home/admin-ata168/pytorch-semseg/pytorch-semseg/ptsemseg/loader/pascal_voc_loader.py", line 199, in setup_annotations
    path = pjoin(sbd_path, "dataset/train.txt")

  File "/home/admin-ata168/anaconda3/envs/pytorch-semseg/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)

TypeError: expected str, bytes or os.PathLike object, not NoneType
```

My config file: 
```
model:
    arch: pspnet
data:
    dataset: pascal
    train_split: train_aug
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: /home/admin-ata168/pytorch-semseg/datasets/VOC/VOCdevkit/VOC2012/
    sbd_path: /home/admin-ata168/pytorch-semseg/datasets/VOC/benchmark_RELEASE/
training:
    train_iters: 300000
    batch_size: 1
    val_interval: 1000
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: /home/admin-ata168/pytorch-semseg/pretrained_models/pspnet_101_pascalvoc.pth
```
I downloaded the dataset from:
PASCAL devkit 2012 [[Here](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html#data)] and the sbd dataset [[Here](http://home.bharathh.info/pubs/codes/SBD/download.html)]

I am using the pretrained model shared [here](https://github.com/meetshah1995/pytorch-semseg/pull/81#issue-182596843)
