### ISSUE TITLE
Cityscapes Config YAML

### ISSUE THREAD

**Issue by alvinwan** [meetshah1995/pytorch-semseg#198]
Here is the config I used to get the repo up and running:

```
model:
    arch: frrnB
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /your/path/to/cityscapes
training:
    train_iters: 85000
    batch_size: 2
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 1.0e-4
        name: adam
    lr_schedule:
        name: poly_lr
        max_iter: 85000
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
    n_workers: 2
    loss:
        name: cross_entropy
```

This may resolve #149 but per #57 may not see meaningful results. Including this here for posterity; I'll include my checkpoint if it looks promising. If I don't followup, training likely gave the same result as the linked thread.
